apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: monitoring
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:4.0
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: graylogpasswordsecret
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 5D5E792708BFA15F0AB42E817B4E69379777D2722E0529DFB031C0B847DB137D
        - name: "GRAYLOG_WEB_LISTEN_URI"
          value: "http://192.168.86.105:32000"
        - name: "GRAYLOG_WEB_LISTEN_URI"
          value: "http://192.168.86.105:32000/"
        - name: GRAYLOG_MONGO_URI
          value: mongodb://mongo:27017/graylog
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://elastic:elasticpwd@elas:9200
        ports:
        - containerPort: 9000
          name: web
        - containerPort: 12201
          name: gelf
      #   volumeMounts:
      #   - name: graylog-certs
      #     mountPath: /etc/graylog/certs
      # volumes:
      # - name: graylog-certs
      #   secret:
      #     secretName: elastic-certs
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: monitoring
  labels:
    app: graylog
spec:
  type: NodePort
  ports:
  - port: 9000
    name: web
    nodePort: 32000
  - port: 12201
    name: gelf
  selector:
    app: graylog