version: '3.3'

services:
  graylog-mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - ./graylog/mongodb:/data/db:rw
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
    ports:
      - 27017:27017
    command: "mongod --config /etc/mongo/mongod.conf"
    environment:
      MONGO_INITDB_ROOT_USERNAME: graylog
      MONGO_INITDB_ROOT_PASSWORD: KgDH0WD5x8UnIfFdU1fO

  graylog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    volumes:
      - ./graylog/elasticsearchdata/data:/usr/share/elasticsearch/data:rw
      - ./graylog/elasticsearchdata/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    environment:
      - TZ=Africa/Porto-Novo
      - transport.host=192.168.86.31
      - node.max_local_storage_nodes=4
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - elasticsearch_max_time_per_index=1d
      - elasticsearch_max_number_of_indices=8
      - indices.fielddata.cache.size=20%
      - elasticsearch_shards=1
      - elasticsearch_replicas=1
    ulimits:
      memlock:
        soft: -1
        hard: -1

  graylog:
    image: graylog/graylog:4.0
    restart: always
    volumes:
      - ./graylog/journal:/usr/share/graylog/data/journal:rw
      - ./graylog/config:/usr/share/graylog/data/config:rw
    environment:
      - TZ=Africa/Porto-Novo
      - GRAYLOG_PASSWORD_SECRET=graylogpasswordsecret
      - GRAYLOG_ROOT_PASSWORD_SHA2=5D5E792708BFA15F0AB42E817B4E69379777D2722E0529DFB031C0B847DB137D
      - GRAYLOG_WEB_ENDPOINT_URI=http://localhost:9000/api/
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/
#      - GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=http://192.168.86.31:9000
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://graylog-elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://graylog:KgDH0WD5x8UnIfFdU1fO@graylog-mongo:27017
    depends_on:
      - graylog-mongo
      - graylog-elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 8514:8514
      # Syslog UDP
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp