version: '3.3'

services:
  graylog-mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - ./graylog/mongodb:/data/db:rw
      - ./mongod.conf:/etc/mongo/mongod.conf:ro
    ports:
      - 27017:27017
    command: "mongod --config /etc/mongo/mongod.conf"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: KgDH0WD5x8UnIfFdU1fO

  graylog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    volumes:
      - ./graylog/elasticsearchdata/data:/usr/share/elasticsearch/data:rw
      - ./graylog/elasticsearchdata/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ=Africa/Porto-Novo
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elasticpwd
    ulimits:
      memlock:
        soft: -1
        hard: -1

  graylog:
    image: graylog/graylog:4.0
    restart: always
    volumes:
      - ./graylog/journal:/usr/share/graylog/data/journal:rw
      - ./graylog/config:/usr/share/graylog/data/config:rw
    depends_on:
      - graylog-mongo
      - graylog-elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 8514:8514
      # Syslog UDP
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp