version: '3.3'

services:
  graylog-mongo:
    image: "mongo:3"
    restart: always
    volumes:
      - ./graylog/mongodb:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017
    command: "mongod --config /etc/mongo/mongod.conf"
    environment:
      MONGO_INITDB_ROOT_USERNAME: graylog
      MONGO_INITDB_ROOT_PASSWORD: KgDH0WD5x8UnIfFdU1fO