apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-graylog.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        multiline.parser  docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   Off
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            On
        Annotations         Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Labels              On
        
    [FILTER]
        Name                parser
        Match               kube.*mongo*
        Key_Name            log
        Parser              json
        Reserve_Data        On
        Preserve_Key        Off

    [FILTER]
        Name                nest
        Match               *
        Wildcard            container_name
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes_

    [FILTER]
        Name                modify
        Match               kube.*
        Copy                kubernetes_container_name source
        Add                 host ${HOSTNAME}
#    [FILTER]
#        Name                grep
#        Match               kube.*
#        Exclude             kubernetes_labels_k8s_app  fluent-bit
#        Exclude             kubernetes_labels_k8s_app  fluent-bit-logging

  output-graylog.conf: |
    [OUTPUT]
        Name                   gelf
        Match                  *
        Host                   192.168.86.5
        Port                   12201
        Mode                   tcp
        Gelf_Short_Message_Key log
        Host_Key               host

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   Off