apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: monitoring
  labels:
    app: graylog
  annotations:
    configmap.reloader.stakater.com/reload: "graylog-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:6.1
        command: ["/bin/sh", "-c"]
        args:
          - |
            keytool -importcert -alias elasticsearch-cert -file /usr/share/graylog/data/certs/rootCA.pem -keystore /opt/java/openjdk/lib/security/cacerts -storepass changeit -noprompt && tini -- /docker-entrypoint.sh
        securityContext:
          runAsUser: 0  # Exécution en tant que root pour avoir accès au keystore
        ports:
        - containerPort: 9000
          name: web
        - containerPort: 12201
          name: gelf
        volumeMounts:
        - name: graylog-config
          mountPath: /usr/share/graylog/data/config
        - name: journal
          mountPath: /usr/share/graylog/data/journal
        - name: graylog-certs
          mountPath: /usr/share/graylog/data/certs
      volumes:
      - name: graylog-config
        configMap:
          name: graylog-config
      - name: journal
        persistentVolumeClaim:
          claimName: gray-claim
      - name: graylog-certs
        secret:
          secretName: gray-certs
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: monitoring
  labels:
    app: graylog
spec:
  type: NodePort
  ports:
  - port: 9000
    name: web
    nodePort: 32000
  - port: 12201
    name: gelf
    nodePort: 31002
  selector:
    app: graylog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gray-claim
  namespace: monitoring
  labels:
    app: graylog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  #storageClassName: openebs-hostpath