#!/bin/bash

mkdir certs
cd certs

# Generate Root Key rootCA.key with 2048
openssl genrsa -passout pass:"$1" -des3 -out rootCA.key 2048

# Generate Root PEM (rootCA.pem)
openssl req -passin pass:"$1" -subj "/C=US/ST=Random/L=Random/O=Global Security/OU=IT Department/CN=elas Certificate"  \
-x509 -new -nodes -key rootCA.key -sha256 -days 3000 -out rootCA.pem

# Generate ES Cert
openssl req -subj "/C=US/ST=Random/L=Random/O=Global Security/OU=IT Department/CN=elas"  \
-new -sha256 -nodes -out es.csr -newkey rsa:2048 -keyout es.key

openssl x509 -req -passin pass:"$1" -in es.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out es.crt \
-days 3000 -sha256




curl -X GET "https://elas:9200/_cat/nodes" -u elastic:elasticpwd --cacert config/certs/rootCA.pem

curl -X GET "https://elas:9200/_cat/indices?v" -u elastic:elasticpwd --cacert config/certs/rootCA.pem



openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout elasticsearch.key -out elasticsearch.crt \
  -subj "/CN=elas/OU=IT Department/O=Global Security/L=Random/ST=Random/C=US" \
  -addext "subjectAltName=DNS:elas,DNS:elas.monitoring.svc.cluster.local"

openssl base64 -in elasticsearch.key -out elasticsearch.key.b64 && openssl base64 -in elasticsearch.crt -out elasticsearch.crt.b64

Convert certificate in base64
openssl base64 -in elastic-ca.crt -out elastic-ca.b64 && openssl base64 -in tls.crt -out tls-crt.b64 && openssl base64 -in tls.key -out tls-key.b64